extends:
  - "@commitlint/config-conventional"
parserPreset: conventional-changelog-conventionalcommits
rules:
  type-enum:
    - 2
    - always
    - [
        "build",
        "ci",
        "chore",
        "code",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ]
